version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - "> 2.13.1, < 3"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.2.0, < 17"
  - dependency-name: Xamarin.Forms
    versions:
    - "> 4.0.0.425677, < 5"
