name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: src
    - name: Test with dotnet
      run: dotnet test --configuration Release
      working-directory: src
