name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: src
    - name: Test with dotnet
      run: dotnet test --configuration Release
      working-directory: src
