name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install .NET MAUI workload
      run: dotnet workload restore
      working-directory: src/AppCenterExtensions.Maui
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: src
    - name: Test with dotnet
      run: dotnet test --configuration Release
      working-directory: src
