name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

env:
  VERSION: 5.0.1.${{ github.run_number }}
  NUGET_REPO_URL: 'https://api.nuget.org/v3/index.json'

jobs:

  nuget:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: Install .NET MAUI workload
      run: dotnet workload restore
      working-directory: src/AppCenterExtensions.Maui

    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1

    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: Update Version
      run: |
        @(
          "AppCenterExtensions/AppCenterExtensions.csproj",
          "AppCenterExtensions.AppInsights/AppCenterExtensions.AppInsights.csproj",
          "AppCenterExtensions.Maui/AppCenterExtensions.Maui.csproj",
          "AppCenterExtensions.XamarinForms/AppCenterExtensions.XamarinForms.csproj"
        ) | ForEach-Object { ((Get-Content -Path $_ -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path $_ }
      working-directory: src

    - name: Build
      run: dotnet build -c Release /p:UseSourceLink=true src/AppCenterExtensions.sln -p:PackageVersion="${{ env.VERSION }}"

    - name: Package
      run: dotnet pack --no-build -c Release /p:UseSourceLink=true src/AppCenterExtensions.sln -p:PackageVersion="${{ env.VERSION }}"

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CLI Tool
        path: |
          **/*.nupkg
          src/README.md

    - name: Push packages to NuGet
      run: |
        @(
          "AppCenterExtensions/bin/Release/AppCenterExtensions.${{ env.VERSION }}.nupkg",
          "AppCenterExtensions.AppInsights/bin/Release/AppCenterExtensions.AppInsights.${{ env.VERSION }}.nupkg",
          "AppCenterExtensions.Maui/bin/Release/AppCenterExtensions.Maui.${{ env.VERSION }}.nupkg",
          "AppCenterExtensions.XamarinForms/bin/Release/AppCenterExtensions.XamarinForms.${{ env.VERSION }}.nupkg"
        ) | ForEach-Object { dotnet nuget push $_ -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_REPO_URL }} --no-symbols true }
      working-directory: src
      continue-on-error: true

  tag:
    needs: nuget
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ env.VERSION }}",
            sha: context.sha
          })
